version: '3.1'

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.5.6
    container_name: orthanc
    command: /etc/orthanc/
    restart: always
    environment:
        username: orthanc
        password: orthanc
    ports:
        - "4242:4242"
        - "8042:8042"